# Site settings
title: "Memory Wheel"
email: "wynkoop+memwheel@gmail.com"
description: "EPIC CINEMATIC RETRO PLANETARIUM MUSIC"
baseurl: "/test02"
url: "https://maxmace.github.io"
permalink: /:categories/:title/

# Social media profiles
github_username: "maxmace"

# Address information
address_street: ""
address_city: "West Melbourne"
address_state: "FL"
address_zip: ""

# show or hide video in ABOUT section
show_featured_video: true

social:
  - title: youtube
    url: https://www.youtube.com/@MemoryWheelMusic
  - title: envelope
    url: "mailto:wynkoop+memwheel@gmail.com?subject=Attention:%20Memory%20Wheel"
# - title: instagram
#   url: https://instagram.com/hidden

# Build settings
markdown: kramdown
highlighter: rouge

# This line tells GitHub which theme to fetch!
remote_theme: "raviriley/agency-jekyll-theme"

# Exclude metadata from the final build
exclude:
  - .github
  - Gemfile
  - Gemfile.lock

# Plugins must be listed for the remote theme to work
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
