# Site settings
title: "Memory Wheel"
email: "wynkoop+memwheel@gmail.com"
description: "EPIC CINEMATIC RETRO PLANETARIUM MUSIC"
baseurl: "/test02"
url: "https://maxmace.github.io"

# Social media profiles
github_username: "maxmace"

# Address information
address_street: ""
address_city: "West Melbourne"
address_state: "FL"
address_zip: ""

# Build settings
markdown: kramdown
highlighter: rouge

# This line tells GitHub which theme to fetch!
remote_theme: "raviriley/agency-jekyll-theme"

# Exclude metadata from the final build
exclude:
  - .github
  - Gemfile
  - Gemfile.lock

# Plugins must be listed for the remote theme to work
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
